
name: master-thesis-kucerenko
channels:
  - defaults
  - conda-forge
  - anaconda
  - pytorch
dependencies:
  - python=3.10
  - jupyter
  - numpy
  - pandas
  - openpyxl
  - scikit-learn
  - matplotlib
  - pytorch
  - torchvision
  - nibabel
  - pyyaml
  - tqdm
  - pip
  - pip:
    - nbimporter
