
name: ma-kucerenko
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.10
  - jupyter
  - numpy
  - pandas
  - openpyxl
  - scikit-learn
  - matplotlib
  - nibabel
  - pyyaml
  - pip
  - pip:
    - nbimporter
