
data:
  file_format: 'nii'
  preprocessing:
    resize:
      target_img_size: [ 64,64 ]
      interpolation_method: 'bicubic'
      # options for interpolation_method:
      #     'nearest', 'nearest-exact', 'bilinear', 'bicubic', 'box', 'hamming', and 'lanczos'
  test_to_train_split_size_percent: 0.3  # ratio of test split to train split
  valid_to_train_split_size_percent: 0.15  # ratio of validation split to train split

model:
  name: 'custom'
  training_params:
    lr: 0.0001
    epochs: 30
    batch_size: 64 # better performance than for 32

# ATTENTION: When overriding values from base_config.yaml in custom yaml files,
#             provide the ENTIRE subtree of the affected root key
#   -> base_config root key subtrees are updated by REPLACING with custom config subtree
