
#   Syntax rules for custom config file:
#   required keys are: 'experiment_name', 'images_dir', 'labels_filepath'

experiment_name: rigid_3d

images_dir: /Users/aleksej/IdeaProjects/master-thesis-kucerenko/UKE_SPECT/rigid/3d
labels_filepath: /Users/aleksej/IdeaProjects/master-thesis-kucerenko/UKE_SPECT/scans_20230424.xlsx
