
#   Syntax rules for this file; required keys are:
#      'num_randomizations', 'interpolation_method', 'batch_size', 'images_dir', 'labels_filepath', 'strategy'

#   Number of experiments to be performed using different randomizations

num_randomizations: 10

# ---------------------------------------------------------------------------------------------

#   Paths

images_dir: /Users/aleksej/IdeaProjects/master-thesis-kucerenko/affine_2d
labels_filepath: /Users/aleksej/IdeaProjects/master-thesis-kucerenko/scans_20230424.xlsx

# ---------------------------------------------------------------------------------------------

#   Data-related

# interpolation_method can be: 'nearest', 'nearest-exact', 'bilinear',
#                               'bicubic', 'box', 'hamming', and 'lanczos'
interpolation_method: 'bicubic'

# ---------------------------------------------------------------------------------------------

#   Model-related

strategy: 'pca_rfc'

num_pca_components: 10

# only used if strategy = 'baseline' ; options: 'majority', 'random'
label_selection_strategy_train: 'random'
label_selection_strategy_valid: 'random'

batch_size: 64  # better performance than for 32

# ---------------------------------------------------------------------------------------------
