
#   Syntax rules for this file; required keys are:
#      'target_img_size', 'interpolation_method', 'test_to_train_split_size_percent',
#      'valid_to_train_split_size_percent', 'model_name', 'lr', 'epochs', 'batch_size', 'images_dir', 'labels_filepath'

#   Number of experiments to be performed using different randomizations

num_randomizations: 3

# ---------------------------------------------------------------------------------------------

#   Paths

images_dir: /Users/aleksej/IdeaProjects/master-thesis-kucerenko/affine_2d
labels_filepath: /Users/aleksej/IdeaProjects/master-thesis-kucerenko/scans_20230424.xlsx

# ---------------------------------------------------------------------------------------------

#   Data-related

target_img_size: [ 224,224 ] # for Resnet

# interpolation_method can be: 'nearest', 'nearest-exact', 'bilinear',
#                               'bicubic', 'box', 'hamming', and 'lanczos'
interpolation_method: 'bicubic'

# ---------------------------------------------------------------------------------------------

#   Model-related

model_name: 'resnet18' # options: 'custom', 'resnet18', 'resnet34'
starting_weights_path: null # path to weights to load as initial weights for training; set null to omit
pretrained: False
strategy: 'regression' # options:
            #   'baseline' -> 1 output binary classification neuron
            #   'regression' -> 1 output regression neuron
            #   'some-other' -> 3 output neurons; nominal multi-class classification (BAUSTELLE)

# only used if strategy = 'baseline' ; options: 'majority', 'random'
label_selection_strategy_train: 'random'
label_selection_strategy_valid: 'random'

lr: 0.0001
epochs: 50
batch_size: 64  # better performance than for 32

# ---------------------------------------------------------------------------------------------
