experiment_name: rigid_3d

paths:
  images: /Users/aleksej/IdeaProjects/master-thesis-kucerenko/UKE_SPECT/rigid/3d
  labels_file: /Users/aleksej/IdeaProjects/master-thesis-kucerenko/UKE_SPECT/scans_20230424.xlsx
