
paths:
  images: /Users/aleksej/IdeaProjects/master-thesis-kucerenko/UKE_SPECT/rigid/3d
  labels_file: /Users/aleksej/IdeaProjects/master-thesis-kucerenko/UKE_SPECT/scans_20230424.xlsx

data:
  file_format: 'nii'
  preprocessing:
    target_img_size: [64,64]
  test_to_train_split_size_percent: 0.4  # ratio of test+validation splits to train split
  valid_to_test_split_size_percent: 0.5  # ratio of validation split to train split

model:
  training_params:
    lr: 0.0001
    epochs: 30
    batch_size: 64 # better performance than for 32
