batch_size: 64
epochs: 20
num_randomizations: 10
images_dir: /Users/aleksej/IdeaProjects/master-thesis-kucerenko/affine_2d
interpolation_method: bicubic
label_selection_strategy_train: random
label_selection_strategy_valid: random
labels_filepath: /Users/aleksej/IdeaProjects/master-thesis-kucerenko/scans_20230424.xlsx
lr: 0.0001
model_name: resnet18
pretrained: false
starting_weights_path: null
strategy: regression
target_img_size:
- 224
- 224
